# Generated by Django 5.2.6 on 2025-09-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Owner's business name", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Owner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OwnerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=512)),
                ('address_line2', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('pincode', models.CharField(max_length=32)),
                ('country', models.CharField(default='India', max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='owners.owner')),
            ],
            options={
                'db_table': 'owner_address',
                'ordering': ['owner', 'city'],
            },
        ),
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='owners.owner')),
            ],
            options={
                'db_table': 'owner_contact',
                'ordering': ['owner', 'name'],
            },
        ),
    ]
