# Generated by Django 5.2.6 on 2025-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealhoarding',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
