# Generated by Django 5.2.6 on 2025-09-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_dealhoarding_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealhoarding',
            name='booked_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
