# Generated by Django 5.2.6 on 2025-09-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_dealhoarding_booked_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
