# Generated by Django 5.2.6 on 2025-09-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoardingimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hoardingimage',
            name='image',
            field=models.ImageField(null=True, upload_to='hoardings_images'),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='master_img_url',
            field=models.ImageField(null=True, upload_to='hoardings_images'),
        ),
    ]
