# Generated by Django 5.2.6 on 2025-09-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('office', 'Office'), ('other', 'Other')], default='office', max_length=32)),
                ('address_line1', models.CharField(max_length=512)),
                ('address_line2', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('pincode', models.CharField(max_length=32)),
                ('country', models.CharField(default='India', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_address',
                'ordering': ['customer', 'city'],
            },
        ),
    ]
